# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Pavel
open_collective: # Pavel
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Pavel
issuehunt: # Pavel
otechie: # Pavel
custom: ["https://www.paypal.com/paypalme/CloudCode1"
